# Generated by Django 4.2 on 2023-07-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
