# Generated by Django 4.2 on 2023-07-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dht_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dht',
            options={'ordering': ('-created',)},
        ),
    ]
